### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nkinar** [sdkcarlos/HoldOn.js#5]
Thanks for this really useful javascript library!  I've looked at the docs, but I can't seem to find a license.  Is the license MIT (similar to the other projects on here)?  Can a license statement be added to the docs?

**Comment by sdkcarlos** [comment]
I'm not a fan of licences, but in this repo I would say [WTFPL](https://en.m.wikipedia.org/wiki/WTFPL) (Do What The Fuck You Want To Public License). So do whatever you want with the code in this repo!

**Comment by nkinar** [comment]
Great, thanks, Carlos.  Although the WTFPL is OK, I will still provide a link back to your Github repo in any README shipped with my code.   Thanks again.
